// <auto-generated />
using System;
using EfCoreRemoveMigrationSnapshot;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EfCoreRemoveMigrationGuidSnapshotIssue.Migrations
{
    [DbContext(typeof(MySqlDbContext))]
    [Migration("20200912194229_InitialCreation")]
    partial class InitialCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EfCoreRemoveMigrationSnapshot.EntityWithGuid", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid?>("OptionalGuid")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RequiredGuid")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("EntitiesWithGuid");
                });
#pragma warning restore 612, 618
        }
    }
}
